language: node_js
node_js:
  - "16.15.0"
services:
  - xvfb
cache:
  npm: true
  directories:
    - node_modules
script:
  - npm ci
  - cd apps/browser/
  - npm run build
  - npm run test
  - cd ../..
  - npm run lint
