name: Quality Checks

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality_checks:
    name: Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.15.0'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run : npm run lint

    - name: Test
      run: |
        cd apps/browser/
        yarn test
